
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package movies;

import java.util.Map;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

import org.jpl7.*;

public class similerMovies_frm extends javax.swing.JFrame {

    public similerMovies_frm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        movieTxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        recommendBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        moviesLst = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Type in a movie you like");

        recommendBtn.setText("Recommend");
        recommendBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                recommendBtnMouseClicked(evt);
            }
        });
        recommendBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recommendBtnActionPerformed(evt);
            }
        });

        moviesLst.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                moviesLstMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(moviesLst);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(movieTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 438, Short.MAX_VALUE))
                        .addGap(33, 33, 33)
                        .addComponent(recommendBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(304, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(movieTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(recommendBtn))
                .addGap(35, 35, 35)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE)
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void recommendBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recommendBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_recommendBtnActionPerformed

    private void recommendBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_recommendBtnMouseClicked
        String movieName = movieTxt.getText().trim();
        
        if(movieName.isEmpty())
            JOptionPane.showMessageDialog(this,"Please Enter a Movie name", "Error",JOptionPane.INFORMATION_MESSAGE);
        else
        {
            Query q1 = new Query("consult('movies.pl')");
            q1.hasSolution();
            
            String str = "same(" + "'" + movieName + "'" + ",SameMovie)";
            q1 = new Query(str);
            
            if(q1.hasSolution())
        {
            Map<String, Term>[] res = q1.allSolutions();
               
            DefaultListModel moviesLstModel = new DefaultListModel();
            for(int i=0; i<res.length; i++){
                moviesLstModel.addElement(removeQuotes(res[i].get("SameMovie").toString()));
            }
            
            moviesLst.setModel(moviesLstModel);
        }
        else
            JOptionPane.showMessageDialog(this,"No Movies Found", "Error",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_recommendBtnMouseClicked

    private void moviesLstMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_moviesLstMouseClicked
        String movieName = moviesLst.getSelectedValue();
        new displayMovie_frm(movieName).setVisible(true);
    }//GEN-LAST:event_moviesLstMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(similerMovies_frm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(similerMovies_frm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(similerMovies_frm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(similerMovies_frm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new similerMovies_frm().setVisible(true);
            }
        });
    }
    
    public static String removeQuotes(String str)
    {
        String res = "";
        for(int i=1; i<str.length()-1; i++)
            res += str.charAt(i);
        return res;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField movieTxt;
    private javax.swing.JList<String> moviesLst;
    private javax.swing.JButton recommendBtn;
    // End of variables declaration//GEN-END:variables
}
